//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Usuarios
    {
        public long Id { get; set; }
        public long IdEmpresa { get; set; }
        public string Nombre { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Cat_Empresa Cat_Empresa { get; set; }
    }
}
