//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamenEntities : DbContext
    {
        public ExamenEntities()
            : base("name=ExamenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cat_Departamento> Cat_Departamento { get; set; }
        public virtual DbSet<Cat_Empleados> Cat_Empleados { get; set; }
        public virtual DbSet<Cat_Empresa> Cat_Empresa { get; set; }
        public virtual DbSet<Cat_Genero> Cat_Genero { get; set; }
        public virtual DbSet<Cat_Usuarios> Cat_Usuarios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VEmpeladosWeb> VEmpeladosWeb { get; set; }
    }
}
